export const REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "USER_LOGOUT_REQUEST";
export const LOGOUT_FAILURE = "USER_LOGOUT_REQUEST";

export const GETALL_REQUEST = "USER_GETALL_REQUEST";
export const GETALL_SUCCESS = "USER_GETALL_SUCCESS";
export const GETALL_FAILURE = "USER_GETALL_FAILURE";

export const DELETE_REQUEST = "USER_DELETE_REQUEST";
export const DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const DELETE_FAILURE = "USER_DELETE_FAILURE";
