export const REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAIL = "USER_REGISTER_FAILURE";

export const AUTH_ERROR = "AUTH_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAIL = "USER_LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "USER_LOGOUT_REQUEST";
export const LOGOUT_FAIL = "USER_LOGOUT_REQUEST";

export const GETALL_SUCCESS = "USER_GETALL_SUCCESS";
export const GETALL_FAIL = "USER_GETALL_FAILURE";

export const DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const DELETE_FAIL = "USER_DELETE_FAILURE";
